### ISSUE TITLE
Cloudflare issue

### ISSUE THREAD

**Issue by KingJune28** [zLeki/DxTrade-Api-Go#6]
1.	WebSocket: bad handshake Error
When trying to establish a WebSocket connection with the server, the connection fails, and the error message “websocket: bad handshake” is shown. It seems the HTTP upgrade request is not being handled properly by the server.
	2.	Login Fails with 403 Forbidden
During the login process, the API responds with a 403 Forbidden error, and the WebSocket connection terminates shortly after with a close 1000 (normal) message. Here are the headers for the request and response:
Request Headers:   

```
POST /api/auth/login HTTP/1.1
Host: dxtrade.ftmo.com
Accept-Encoding: gzip, deflate, br, zstd
Accept: */*
Content-Type: application/json
DNT: 1
Cookie: {JSESSIONID=xxxx; DXTFID=xxxx; __cf_bm=xxxx; cf_clearance=xxxx}
```
Expected Behavior:

	1.	The WebSocket connection should succeed with the appropriate HTTP status code of 101 Switching Protocols.
	2.	The login process should return a 200 OK with valid session cookies and proceed with further actions.

Actual Behavior:

	1.	The WebSocket connection fails with the error websocket: bad handshake, which indicates that the handshake was not completed successfully.
	2.	Login fails with a 403 Forbidden response, preventing further actions.

**Comment by benjaminsabella** [comment]
So, unfortunately this issue is occurring because FTMO has re-enabled their Cloudflare again. The only thing I can recommend is to go back a couple versions on the main branch to find the Cloudflare bypass version, but it requires a Zen rows API key which they should still have a 14-day free trial then it's like 50$ a month. I wish there was an alternative to get around Cloudflare but there's nothing to my understanding.

**Comment by benjaminsabella** [comment]
Here's the [version](https://github.com/zLeki/DxTrade-Api-Go/tree/224e76d3e59e409ebeeb577c66893518ea639196)
