### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by Shivamvrewa** [zLeki/DxTrade-Api-Go#8]
Hi
I am getting error when i try to connect Dxtrade '
Post "https://dxtrade.com/api/auth/login": dial tcp 185.79.218.182:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
I am using server as "dxtrade.com"

**Comment by benjaminsabella** [comment]
Hi, does your login page look like this? Because I believe the host your trying to connect to doesn't support the login function. Your login page should look like what I attached below. I'm also going to close your other issue since you made a new one.
<img width="783" alt="Screenshot 2024-11-09 at 12 41 51 PM" src="https://github.com/user-attachments/assets/9c00f8ba-bbf9-4998-9f29-f10898de51c2">

**Comment by Shivamvrewa** [comment]
No, Can you please share the name of broker with server. 
also can you give me server details of Derivx and jetvix  Broker.

**Comment by benjaminsabella** [comment]
Could you provide the url to your broker?
